"attribute" = "blue0"
"comment" = { fg = "pink1", modifiers = ["italic"]  }
"constant" = { fg = "orange0" }
"constant.builtin" = { fg = "orange0", modifiers = ["bold"] }
"constant.character.escape" = { fg = "orange0", modifiers = ["bold"] }
"constant.numeric" = "orange0"
"constructor" = { fg = "blue0", modifiers = ["bold"] }
"function" = { fg = "green0", modifiers = ["bold"] }
"function.builtin" = "green0"
"function.macro" = "green0"
"keyword" = { fg = "orange1" }
"label" = "blue0"
"module" = "blue0"
"namespace" = "pink2"
"operator" = "orange1"
"punctuation" = "orange1"
"special" = "pink2"
"string" = "violet0"
"tag" = "green0"
"type" = "blue0"
"type.builtin" = "orange0"
"variable" = "white0"
"variable.builtin" = "blue0"
"variable.other.member" = "blue0"
"variable.parameter" = "green1"

"diff.delta" = "violet0"
"diff.minus" = "pink2"
"diff.plus" = "green1"

"error" = "orange1"
"hint" = "white0"
"info" = "blue0"
"warning" = "green1"

"ui.background" = { bg = "dark_red0" }
"ui.cursor.match" = { bg = "pink3", fg = "dark_red0" }
"ui.cursor.primary" = { bg = "pink3", fg = "dark_red0" }
"ui.cursorline" = { bg = "dark_red3" }
"ui.help" = { bg = "dark_red3", fg = "white0" }
"ui.linenr" = { fg = "white0" }
"ui.linenr.selected" = { fg = "pink4" }
"ui.menu" = { fg = "white0", bg = "dark_red4" }
"ui.menu.selected" = { fg = "orange1", bg = "dark_red2", modifiers = ["bold"] }
"ui.popup" = { bg = "dark_red3" }
"ui.selection" = { bg = "dark_red1" }
"ui.statusline" = { fg = "dark_red0", bg = "pink1" }
"ui.statusline.inactive" = { fg = "dark_red0", bg = "pink0" }
"ui.statusline.insert" = { fg = "dark_red0", bg = "green0" }
"ui.statusline.normal" = { fg = "dark_red0", bg = "pink1" }
"ui.statusline.select" = { fg = "dark_red0", bg = "blue0" }
"ui.text" = { fg = "white0" }
"ui.text.focus" = { fg = "orange1" }
"ui.virtual.inlay-hint" = { fg = "blue0" }
"ui.virtual.ruler" = { bg = "dark_red3" }
"ui.virtual.whitespace" = "dark_red5"
"ui.window" = { bg = "dark_red3" }

"diagnostic.error" = { underline = { color = "orange1", style = "double_line" } }
"diagnostic.hint" = { underline = { color = "white0", style = "double_line" } }
"diagnostic.info" = { underline = { color = "blue0", style = "double_line" } }
"diagnostic.warning" = { underline = { color = "green1", style = "double_line" } }

"markup.bold" = { modifiers = ["bold"] }
"markup.heading" = { fg = "orange1", modifiers = ["bold"] }
"markup.italic" = { modifiers = ["italic"] }
"markup.link.text" = "green1"
"markup.link.url" = { fg = "blue0", modifiers = ["underlined"] }
"markup.raw" = "pink2"
"markup.strikethrough" = { modifiers = ["crossed_out"] }

[palette]
blue0 = "#3e968c"
dark_red0 = "#190f0f"
dark_red1 = "#211616"
dark_red2 = "#261516"
dark_red3 = "#2d1718"
dark_red4 = "#442022"
dark_red5 = "#492a2c"
green0 = "#87a242"
green1 = "#6db269"
orange0 = "#d15a3a"
orange1 = "#ea8024"
pink0 = "#622b30"
pink1 = "#963e48"
pink2 = "#d95362"
pink3 = "#b2696d"
pink4 = "#e35968"
violet0 = "#be6680"
white0 = "#cebabf"
