[[language]]
name = "json"
language-server = { command = "vscode-json-languageserver", args = ["--stdio"] }

[[language]]
name = "css"
language-server = { command = "css-language-server", args = ["--stdio"] }

[[language]]
name = "html"
language-server = { command = "html-language-server", args = ["--stdio"] }

[[language]]
name = "bash"
auto-format = true
indent = { tab-width = 4, unit = "    " }
formatter = { command = "shfmt", args = ["-s", "-i", "4"] }

[[language]]
name = "python"
auto-format = true
formatter = { command = "black", args = ["--quiet", "-"] }

[[language]]
name = "git-ignore"
file-types = [".gitignore", ".gitignore_global", ".fdignore"]

[[language]]
name = "xml"
file-types = ["xml", { suffix = "fontconfig/fonts.conf" }]

[[language]]
name = "nix"
file-types = ["nix", { suffix = "picom/picom.conf" }]

[[language]]
name = "ini"
file-types = ["ini", { suffix = "redshift/redshift.conf" }]
