[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt", args = ["-s"] }
file-types = ["sh", "bash", "zsh", ".bash_login", ".bash_logout", ".bash_profile", ".bashrc", ".profile", ".zshenv", ".zlogin", ".zlogout", ".zprofile", ".zshrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc", ".bash_aliases", "template"]

[[language]]
name = "python"
auto-format = true
formatter = { command = "yapf" }

[[language]]
name = "git-ignore"
file-types = [".gitignore", ".gitignore_global", ".fdignore"]

[[language]]
name = "xml"
file-types = ["xml", "musicxml"]

[[language]]
name = "nix"
file-types = ["nix", { suffix = "picom/picom.conf" }]

[[language]]
name = "ini"
file-types = ["ini", "desktop", { suffix = "redshift/redshift.conf" }]

[[language]]
name = "json"
file-types = ["json", "jsonc", "arb", "ipynb", "geojson", { suffix = "waybar/config" }]
